### ISSUE TITLE
Converted models

### ISSUE THREAD

**Issue by kroggen** [ankan-ban/llama_cu_awq#1]
Great work!

Any chance to get the converted models on huggingface?

It is being a pain to get the proper environment just to make the conversion...

**Comment by kroggen** [comment]
I found [this one](https://huggingface.co/abhinavkulkarni/meta-llama-Llama-2-7b-chat-hf-w4-g128-awq) but it is a single Pytorch bin file, and the convertor here expect many files

**Comment by kroggen** [comment]
OK, I was able to do it using the above model

Here are the steps I used:

```
git clone https://github.com/ankan-ban/llama_cu_awq
gcc weight_packer.cpp -o weight_packer
nvcc -O3 llama2_q4.cu -o llama2_q4
cd ..

mkdir models
cd models
wget https://huggingface.co/abhinavkulkarni/meta-llama-Llama-2-7b-chat-hf-w4-g128-awq/resolve/main/pytorch_model.bin
wget https://huggingface.co/abhinavkulkarni/meta-llama-Llama-2-7b-chat-hf-w4-g128-awq/resolve/main/config.json

python3 ../llama_cu_awq/convert_awq_to_bin.py pytorch_model.bin output
../llama_cu_awq/weight_packer config.json output llama2-7b-awq-q4.bin

cd -
./llama2_q4 ../models/llama2-7b-awq-q4.bin 256 "write an essay about GPUs"
```

But there were lots of errors because I am using Linux and your code contains some functions for Windows only. I will send a PR with the changes

**Comment by ankan-ban** [comment]
Thanks @kroggen for your changes. It certainly makes easier for people to use this repo!
