### ISSUE TITLE
Inference problem consulting

### ISSUE THREAD

**Issue by jaycase111** [ankan-ban/llama_cu_awq#21]
Hello, thank you very much for your work to give me a lot of help, but I have a question, hope you can answer:
<img width="937" alt="image" src="https://github.com/ankan-ban/llama_cu_awq/assets/43005515/a9099fcf-7060-4730-9bc2-03204f41bc28">
<img width="543" alt="image" src="https://github.com/ankan-ban/llama_cu_awq/assets/43005515/192c1a1a-6a5b-4461-bdab-da83a81c2ffd">

Why is there no residual addition operation in your inference code, but the generated result is normal? Thank you and wish you a happy life!

**Comment by ankan-ban** [comment]
the residual add operation is done in the matmul kernel call (just above the line you highlighted). The last param to the matmul call (true) indicates that a fused residual add operation has to be performed.

**Comment by jaycase111** [comment]
OK、Thank you!!!
